{% set name = "lbl-repack" %}
{% set version = "1.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5832c9bf28bd4a77426479cc6d6fc2a069a87b50b89715cd819d9a0de653ed32

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py<35]
  entry_points:
    - repack = repack.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - numpy
    - pip
    - python
  run:
    - numpy >=1.13.3
    - python
    - scipy >=0.17.1

test:
  imports:
    - repack

about:
  home: https://github.com/pcubillos/repack
  summary: A line-transition data compression package
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pcubillos/repack

extra:
  recipe-maintainers:
    - pcubillos
